version: '2.4'
services:
  db:
    container_name: db
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: retencja
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/retencja
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/retencja
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
